# Generated by Django 4.1 on 2022-08-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_options_livros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name_plural': 'Livros'},
        ),
        migrations.AddField(
            model_name='livros',
            name='autores',
            field=models.ManyToManyField(related_name='Livros', to='core.autor'),
        ),
    ]
